[package]
name = "aoc07"
version = "0.1.0"
authors = ["Olly Swanson <olly.swanson95@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.7.2"
regex = "1.4.5"
